### ISSUE TITLE
Request for Cell-Type Annotation File

### ISSUE THREAD

**Issue by yunshanglzy** [tanaylab/EmbExe#1]
Hi,

Thank you for sharing your inspiring work on ExE development. I have been exploring this area and recently downloaded the dataset from GEO (GSE267870). However, I couldn’t find detailed cell-type annotations for individual cells, such as which ones correspond to uncommitted EPCs.

Would it be possible to share a file or provide additional information about the cell-type annotations?

I truly appreciate your time and effort, and I look forward to your guidance.

Best regards,

**Comment by aviezerl** [comment]
[Metadata_embexe_atlas.csv](https://github.com/user-attachments/files/18109191/Metadata_embexe_atlas.csv)
Attached. 

Best, 
Aviezer

**Comment by yunshanglzy** [comment]
Thank you! This is very helpful😊
